### ISSUE TITLE
Can you tell  me how to server this on my own server?

### ISSUE THREAD

**Issue by wandergis** [lukasmartinelli-alt/glfonts#1]
This is the solution what i want!! Thanks a lot,but how can i server the font service on my own server? Just like this.
`http://glfonts.lukasmartinelli.ch/fonts/{fontstack}/{range}.pbf`

**Comment by lukasmartinelli** [comment]
> This is the solution what i want!! Thanks a lot,but how can i server the font service on my own server? Just like this.

Good. Actually just clone this repo and throw it on any HTTP server. That's it.
Can be a static NGINX or also S3 or what else you have lying around.

For example this here is hosted directly by GitHub pages by GitHub.
